version: '3.7'
services:
  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - 5000:5000
    environment:
      - DB_HOST=db
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
